### ISSUE TITLE
Url value from Lume 

### ISSUE THREAD

**Issue by oscarotero** [dragonwocky/psyche#1]
Hi, see that you use this code to get the urls of the pages:
https://github.com/dragonwocky/psyche/blob/53f44fd2b5b716877402a148662e93c7dca0143a/indexers/lume.ts#L65-L67

In Lume, all pages have a `url` value with the public url, so you could do simply:

```ts
const url = page.data.url;
```

But it could happen that the site is published in a subdirectory (like `https://example.com/blog/`) so all urls should prepend the `/blog` subdirectory. A more strong way to get the url is:

```ts
const url = site.url(page.data.url);
```

`site.url()` returns the final url of any path, prepending subdirectories if needed.

**Comment by dragonwocky** [comment]
Thanks! I've patched this.
